#!/bin/bash

DIRECTORY=$HOME/Documents/Scripts

case "$1" in
	'-m' | '--modify' )
		if [ -f $DIRECTORY/$2 ]; then
			nano $DIRECTORY/$2
		else
			echo "Script $2 does not exist (#1)!"
			exit 1
		fi
		;;
	'-c' | '--create' )
		if [ ! -f $DIRECTORY/$2 ]; then
			nano $DIRECTORY/$2
		else
			echo "Script $2 exist! (#2)"
			exit 1
		fi
		;;
	'-r' | '--remove' )
		if [ -f $DIRECTORY/$2 ]; then
			while true; do
				read -p "Are you sure to remove this script? (n)" yn
				case $yn in
        				[Yy]* )
						rm $DIRECTORY/$2
						;;
				        * )
						echo "Cancelled. (#3)"
						exit
				esac
			done
		else
			echo "Script $2 does not exist! (#4)"
			exit 1
		fi
		;;
	* )
		if [ -f $DIRECTORY/$1 ]; then
			source $DIRECTORY/$@
		elif [ $1 ]; then
			echo "Script $1 does not exist! (#5)"
			exit 1
		else
			echo "Usage: run [-c|--create|-m|--modify|-r|--remove] scriptname"
		fi
esac
